stage('Terraform Plan') {
    steps {
        withCredentials([[
            $class: 'AmazonWebServicesCredentialsBinding',
            credentialsId: 'aws-credentials'
        ]]) {
            dir('terraform') {
                bat 'terraform plan'
            }
        }
    }
}
